# .github/workflows/flatpak-lint.yml
name: Flatpak Lint

on:
  workflow_dispatch:
  
jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Install Flatpak and Flatpak Builder
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder
          
          flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo

      - name: Install GNOME SDK 46
        run: |
          flatpak install --user flathub org.gnome.Sdk//46 -y

      - name: Install Flatpak Builder
        run: |
          flatpak install --user flathub org.flatpak.Builder -y
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flatpak
        run: |
          flatpak run org.flatpak.Builder --force-clean --sandbox --user --install --install-deps-from=flathub --ccache --mirror-screenshots-url=https://dl.flathub.org/media/ --repo=repo builddir com.jeffser.Alpaca.json

      - name: Lint Flatpak Manifest
        run: |
          flatpak run --command=flatpak-builder-lint org.flatpak.Builder manifest com.jeffser.Alpaca.json
          flatpak run --command=flatpak-builder-lint org.flatpak.Builder repo repo
