# .github/workflows/flatpak-build.yml
name: Flatpak Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Flatpak and Flatpak Builder
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the latest commit ID
        id: get_commit_id
        run: echo "COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Update Flatpak Manifest
        run: |
          sed -i 's|"url" : "file:///home/tentri/Documents/Alpaca"|"url" : "https://github.com/Jeffser/Alpaca"|g' ./com.jeffser.Alpaca.json

      - name: Build Flatpak
        run: |
          flatpak-builder --force-clean --repo=repo builddir ./com.jeffser.Alpaca.json
          
      - name: Upload Flatpak Artifact
        uses: actions/upload-artifact@v2
        with:
          name: flatpak-package
          path: /
