# .github/workflows/meson-build.yml
name: Meson Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure Build with Meson
        run: |
          meson setup builddir

      - name: Build Project with Meson
        run: |
          meson compile -C builddir

      - name: Run Tests with Meson
        run: |
          meson test -C builddir
